### ISSUE TITLE
Change text columns to varchar

### ISSUE THREAD

**Issue by hpatricio** [mtgjson/mtgsqlive#13]
The text is cut at 255 characters, you should alter the column type to varchar in order do parse all text. For example, card "Domri, Chaos Bringer", from RNA set-

**Comment by ZeldaZach** [comment]
Hmm, I swear I fixed this once. If you'd like to put a fix up, I'll gladly review it. Otherwise, I'll see what I can do when I get some more time :)

**Comment by ZeldaZach** [comment]
Just tested and Domri's text is 
```
[+1]: Add {R} or {G}. If that mana is spent on a creature spell, it gains riot. (It enters the battlefield with your choice of a +1/+1 counter or haste.)
[−3]: Look at the top four cards of your library. You may reveal up to two creature cards from among them and put them into your hand. Put the rest on the bottom of your library in a random order.
[−8]: You get an emblem with "At the beginning of each end step, create a 4/4 red and green Beast creature token with trample."
```

Which is all the information, and is correct
