### ISSUE TITLE
Force type of json file to utf-8

### ISSUE THREAD

**Issue by hpatricio** [mtgjson/mtgsqlive#14]
I've had to force the open command to utf-8, it was not reading the file in windows 10. My python setup is anaconda.
i've had to change line 202 to the following: "json_data = json.load(input_file.open("r", encoding='utf-8'))"

**Comment by ZeldaZach** [comment]
If you'd like to PR the encoding change, would be awesome :)

If not, i'll get around to it soon! Appreciate the ticket

**Comment by ZeldaZach** [comment]
Addressed at some point, it's in now :)
