### ISSUE TITLE
Missing Set Translations

### ISSUE THREAD

**Issue by Jaecen** [mtgjson/mtgsqlive#16]
I've downloaded the AllSets Sqlite database from [the MTGJSON download page](https://mtgjson.com/downloads/compiled/). I note that the `set_translations` table is empty and there is no [`translations`](https://mtgjson.com/structures/translations/) table.

**Comment by ZeldaZach** [comment]
I never did get around to that. Good spotting. If you'd like to contribute a change I'd love it, otherwise I'll look into it at some point
