### ISSUE TITLE
Maybe point out cloning with a depth of 1

### ISSUE THREAD

**Issue by shmup** [mtgjson/mtgsqlive#2]
Possibly point out that unless developers want to clone down the now removed AllSets-x.db, they can do a `git clone --depth 1 https://github.com/mtgjson/mtgsqlive.git` to go from a 40+ MB clone to 156KB

Or possibly just prune out the database entirely.

**Comment by ZeldaZach** [comment]
I'll look into removing it shortly. Sorry for the issues this may have caused you!

**Comment by shmup** [comment]
Hey no issues at all. Just passing on a thought is all. Cheers.

**Comment by ZeldaZach** [comment]
I updated the Readme to include this. I tried using `bfg` to remove the file but it didn't seem to work as expected. If you need anything else from me please let me know! Glad knowing somebody is using this project :)

**Comment by shmup** [comment]
You know what, this is strange. I can't get the project size beneath 31 MB. I'm going to have to tinker with this more later.
