### ISSUE TITLE
sets.csv has empty sets

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgsqlive#42]
#### Description of Bug:
sets.csv has sets with 0 `baseSetSize`.

**Comment by omfgitsmark** [comment]
I don't think this is a mtgsqlive issue since that's how it is in JSON as well.
![sets_baseSetSize_0](https://user-images.githubusercontent.com/35660089/72777368-6cf79000-3be3-11ea-811f-7f9f44894fd9.png)

Maybe add a check for `baseSetSize = 0` and if so set it to `totalSetSize`?

**Comment by ZeldaZach** [comment]
baseSetSize indicates how many cards are "expected" to be in a set, based on a card's numbering "XXX/YYY". If there is no YYY, then I can't establish an amount and mark it as 0.
