### ISSUE TITLE
Make comma separated values in a field without spaces

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgsqlive#43]
The fields `colorIdentity`, `colorIndicator` and `colors` have spaces between the values, which throws off things during import.

For example, Mortify’s `colors` is `'W', 'B'`. If we can make it so it has no spaces like `'W','B'` then it would be easier to import with SET and ENUM.

**Comment by omfgitsmark** [comment]
Fixed in #47 

EDIT: I can't close this :(
