### ISSUE TITLE
When importing the "AllPrintings.json.xz" file, all sets starting with set code "R" and later do not import

### ISSUE THREAD

**Issue by pelasace** [mtgjson/mtgsqlive#64]
Using Cockatrice, when importing the file at https://www.mtgjson.com/files/AllPrintings.json.xz , the import is successful, but any set whose set code begins with "R" or any letter after "R" do not import with any cards. The "Manage sets" section shows that their set codes are there, but no names or release dates are associated with them and their cards are missing.

**Comment by ZeldaZach** [comment]
This issue is not relevant to this repository.
