### ISSUE TITLE
faceName missing / sqlite database

### ISSUE THREAD

**Issue by JeromedC34** [mtgjson/mtgsqlive#65]
#### Version(s) affected
- [ ] MTGJSON 4
- [X] MTGJSON 5

#### Version(s) tested against
MTGJSON 5.0.1+20200824
#### Description of Bug
In AllPrintings.sqlite.zip the foreign_data table does not have the faceName field

**Comment by ZeldaZach** [comment]
cc @omfgitsmark can you look into this

**Comment by JeromedC34** [comment]
Hi, @omfgitsmark any news on this issue?

**Comment by ZeldaZach** [comment]
Support was added a while ago

**Comment by JeromedC34** [comment]
Shoudln't be closed, the field faceName is still missing from table foreign_data in sqlite file!
