### ISSUE TITLE
faceName missing / sqlite database

### ISSUE THREAD

**Issue by JeromedC34** [mtgjson/mtgsqlive#68]
The issue #65 was closed today, but it is not resolved.
The faceName field is still missing from the foreign_data table in the sqlite file.

**Comment by JeromedC34** [comment]
@ZeldaZach could you please check it before closing it again?
Or explain why you do so.
Thank you in advance for this.
Thank you for all the work you do.

**Comment by staghouse** [comment]
confirming I am not seeing `faceName` in the `foreign_data` table either

**Comment by ZeldaZach** [comment]
This should be fixed!
