### ISSUE TITLE
Add `setName`

### ISSUE THREAD

**Issue by staghouse** [mtgjson/mtgsqlive#71]
I believe it would be beneficial to include `setName` to database. Right now there is only `setCode` which is more meta-data like than it is useful.

In a particular use case example, when using the SQLite database one has to execute on the cards table, find the set code and then execute on the sets table to match and locate the set name - then do more work to store that upwards.

In short, this is helpful data for any developer in my opinion. Any other thoughts?

**Comment by zebapy** [comment]
Having the set code seems like enough to be an identifier to look up the related table, which seems natural to relational dbs. If you add the set name, you go down the road of adding arbitrary duplicated content across tables. Just my gut reaction here.

**Comment by staghouse** [comment]
This can be solved by some inner join logic, not a big deal
