### ISSUE TITLE
Urabrask the Hidden LIST is missing

### ISSUE THREAD

**Issue by nicho92** [mtgjson/mtgsqlive#77]
I just opend a Urabrask the Hidden (THE LIST - IMA) ... and i can't find it in database.

![image](https://user-images.githubusercontent.com/11507615/166101248-9b4a7416-4f8b-4fae-b090-718d16eddf13.png)

**Comment by nicho92** [comment]
![image](https://user-images.githubusercontent.com/11507615/166101397-cef19e7f-101b-49aa-b7dc-313d9ce963bc.png)

**Comment by zqft9001** [comment]
Appears to now be available (checked in 5.2.0+20220630), see below query:

`SELECT * FROM cards WHERE cards.uuid = "264b3149-1b3c-5d62-9c9e-2961a7310d80";`
