### ISSUE TITLE
60 records in cards table prefix name and number with "A-"

### ISSUE THREAD

**Issue by drewmie** [mtgjson/mtgsqlive#79]
60 records in cards table prefix their name, facename, and number with "A-" (the letter "A" and a hyphen).  You can see all 60 using the following query.

`SELECT * FROM cards WHERE [name] LIKE 'A-%' OR faceName LIKE 'A-%' OR number LIKE 'A-%';
`

For example, one record has name "A-Cloister Gargoyle" instead of "Cloister Gargoyle".

**Comment by zqft9001** [comment]
These are alchemy rebalanced cards, I believe this is expected behavior. Note that the availability is only "arena." You can get the same set with the following query.

`SELECT * FROM cards WHERE cards.isRebalanced = 1;`

**Comment by ZeldaZach** [comment]
This is intentional behavior, yep! Hopefully you're able to work with it @drewmie let me know if you have questions
