### ISSUE TITLE
Some tcgplayer Product IDs are incorrectly populated on cards that don't include the finish of that ID

### ISSUE THREAD

**Issue by drewmie** [mtgjson/mtgsqlive#80]
Some cards populate tcgplayerProductId and tcgplayerEtchedProductId when the row doesn't include the finish of that ID, namely:

1. tcgplayerEtchedProductId sometimes incorrectly populated where etched is not one of the finishes.
2. tcgplayerProductId sometimes incorrectly populated where etched is the only value in finishes.

The effect:  This causes problems when I try to join to collections exports from the tcgplayer app.  The collection's Product ID (which is a single column) ends up joining to rows that don't match its finish.  This issue might be limited to some cards in the SNC and/or CLB sets, but I can't recall.

My workaround:  I used the two queries below to identify the cards records and update the incorrectly populated Product ID to NULL.  My queries also verify that the ID exists on at least one other correct cards record.

```
/*** Set tcgplayerEtchedProductId = NULL when incorrectly populated on non-etched row. ***/
SELECT c.scryfallOracleId ,c.tcgplayerProductId ,c.tcgplayerEtchedProductId ,c.finishes ,c.*
--UPDATE c SET c.tcgplayerEtchedProductId = NULL
FROM dbo.cards c
WHERE c.finishes NOT LIKE '%etched%'
	AND c.tcgplayerEtchedProductId IS NOT NULL
	AND EXISTS ( /*** verifies that this etched ID is correctly populated on an etched row ***/
			SELECT 1
			FROM dbo.cards x
			WHERE x.finishes LIKE '%etched%'
			AND x.tcgplayerEtchedProductId = c.tcgplayerEtchedProductId
			)
ORDER BY c.scryfallOracleId ,c.tcgplayerProductId ,c.tcgplayerEtchedProductId ,c.finishes
;


/*** Set tcgplayerProductId = NULL when incorrectly populated on an etched-only row. ***/
SELECT c.scryfallOracleId ,c.tcgplayerProductId ,c.tcgplayerEtchedProductId ,c.finishes ,c.*
--UPDATE c SET c.tcgplayerProductId = NULL
FROM dbo.cards c
WHERE c.finishes = 'etched'
	AND c.tcgplayerProductId IS NOT NULL
	AND EXISTS ( /*** verifies that this non-etched ID is correctly populated on a row that is not etched-only. ***/
			SELECT 1
			FROM dbo.cards x
			WHERE x.finishes <> 'etched'
			AND x.tcgplayerProductId = c.tcgplayerProductId
			)
ORDER BY c.scryfallOracleId ,c.tcgplayerProductId ,c.tcgplayerEtchedProductId ,c.finishes
;

```

MTGSQLive Output File
(2022-07-28 05:18:51)
MTGJSON Version: 5.2.0+20220728

**Comment by drewmie** [comment]
1st data example: cards with setCode='SLD', number 159 through 163, finishes='nonfoil,foil'.  Column tcgplayerEtchedProductId is populated, but it should be NULL since 'etched' isn't one of the finishes on those rows.

2nd data example is the opposite:  cards with setCode='CLB', number in ('477','497','498','514','516','526','529','547','550'), finishes='etched'.  Column tcgplayerProductId is populated, but it should be NULL since these rows are only for the 'etched' finish.

**Comment by ZeldaZach** [comment]
This should be addressed!
