### ISSUE TITLE
Is there really a need for linking tables?

### ISSUE THREAD

**Issue by ghost** [mtgjson/mtgsqlive#9]
I don't know why there are linking tables. Instead of saving a number for each rarity just save the rarity for the card for example. I was going along with the database created by this script but I've reached the point where I think I'll better rewrite the script to avoid using linking tables when I've tried to query for the cards legal in legacy. I couldn't even find the proper way of doing it:

Maybe something like this which I think is just crazy difficult when it would be very simple if instead of a number the cardLegalFormat actually saved the name of the format and the kind of legality.
```
cardList = cursor.execute("SELECT DISTINCT name
                           FROM cards
                           JOIN lnkCardLegFormat
                             ON card.cId=lnkCardLegFormat.llfId
                           JOIN lnkLegalityFormat
                             ON lnkCardLegFormat.llfId=lnkLegalityFormat.llfId
                           JOIN luLegalities
                             ON luLegalities.legId=lnkLegalityFormat.legId
                           JOIN luFormats
                             ON luFormats.fId=lnkLegalityFormat.fId
                           WHERE luFormats.formatName='Legacy' AND luLegalities.legalityName='Legal'")
```

**Comment by ZeldaZach** [comment]
I plan on rewriting this form scratch once V4 is completed. Hang tight!
