### ISSUE TITLE
AllPrintings.sql missing commit.

### ISSUE THREAD

**Issue by splatterb0y** [mtgjson/mtgsqlive#95]
For people that use "AUTOCOMMIT=0" in mysql import its crucial that the file contains a "commit;" at the end.
It would be great if the new version of the files would contain this again.

I believe the previous versions contained a commit at the end. My automation is only failing since the new version dropped, because the commit is missing, my check for thresholds isn't passed anymore.

**Comment by ZeldaZach** [comment]
I can't seem to find that the previous version had a COMMIT at the end, but I'm happy to add it!
